language: python
python:
  - "pypy3"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - pip install coveralls flake8
  - pip install .

script:
  - flake8 .
  - coverage run --source=flask_ldap3_login setup.py test

after_success: coveralls

before_deploy:
  - git describe --tags > VERSION

deploy:
  provider: pypi
  skip_cleanup: true
  user: nickw444-deploy
  password: "$PYPI_PASSWORD"
  on:
    tags: true
    python: 3.6
